services:
  backend:
    image: capcom6/sms-gateway
    build:
      context: ../..
      dockerfile: ./build/package/Dockerfile
      args:
        - APP=sms-gateway
    environment:
      - DEBUG=
      - CONFIG_PATH=config.yml
      - GOOSE_DBSTRING=sms:sms@tcp(db:3306)/sms
      - HTTP__LISTEN=0.0.0.0:3000
      - DATABASE__HOST=db
      - DATABASE__PORT=3306
      - DATABASE__USER=sms
      - DATABASE__PASSWORD=sms
      - DATABASE__DATABASE=sms
    ports:
      - "3000:3000"
    volumes:
      - ../../configs/config.yml:/app/config.yml:ro
    restart: 'unless-stopped'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:11.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sms
      - MYSQL_USER=sms
      - MYSQL_PASSWORD=sms
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mariadb-data:
